name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17.0'
          java-package: jdk+fx

      - uses: sbt/setup-sbt@v1

      - run: sbt -v update compile
      - run: sbt -v scripted
